### ISSUE TITLE
Basic question

### ISSUE THREAD

**Issue by ib00** [sjb3d/descent#1]
I am new to Rust, using this project to learn more.

Basic questions:
- Do you take the computational graph and then create one kernel on the fly?
- How do you create a simple 2D (or 3D) array with some data?

**Comment by sjb3d** [comment]
Hi,

> Do you take the computational graph and then create one kernel on the fly?

In general multiple kernels are needed.  There is an example of this in the [array_api README](https://github.com/sjb3d/descent/tree/main/examples/array_api), which shows a graph with two "clusters" of nodes. Each cluster is compiled into a kernel at runtime.

> How do you create a simple 2D (or 3D) array with some data?

You can get a rust `io::Write` from a parameter using `Environment::writer(param)`. All the examples use this to load data from files into arrays.

A helper function to create a parameter and immediately copy a rust slice as its data is here: https://github.com/sjb3d/descent/blob/eba9d64ad5196a596f5806e457f02e5241f560d2/src/environment.rs#L204.

Hope that helps!

**Comment by sjb3d** [comment]
I'll close this since the answer above has a 👍, but feel free to re-open if there are more questions!
